### ISSUE TITLE
Eclipse Luna getting protocol_version fatal alert

### ISSUE THREAD

**Issue by rainbow99984** [ecd-plugin/ecd#38]
I'm trying to install the plugin using market place, after searching for the plugin, I selected the plugin to install, the confirm window leads to following error:-
Unable to read repository at https://ecd-plugin.github.io/update/content.xml.
Received fatal alert: protocol_version
.I'm not behind any proxy, using direct connection, able to install other plugins.
Thanks

**Comment by RobertZenz** [comment]
This should be a duplicate of #11 and #29.

**Comment by RobertZenz** [comment]
In case it isn't, drop me a note and I'll test it on Luna. But I do not believe that this is a general problem.

**Comment by rainbow99984** [comment]
Hi, I checked both the suggestions, I have checked my proxy settings and it is selected direct option. I can open market place see the plugin list and search too,  when tried internal browser to open website all worked. but When I tried to open https://ecd-plugin.github.io/update/content.xml I get something like

`&(|(osgi.arch=x86)(osgi.arch=x86_64))(|(osgi.os=linux)(osgi.os=macosx)(osgi.os=win32))) (org.eclipse.update.install.features=true) (&(|(osgi.arch=x86)(osgi.arch=x86_64))(|(osgi.os=linux)(osgi.os=macosx)(osgi.os=win32))) %license %copyright (org.eclipse.update.install.features=true) true %license %copyright (org.eclipse.update.install.features=true) %license %copyright Bundle-SymbolicName: org.sf.feeling.decompiler.source.attach;singleton:=true Bundle-Version: 3.0.0.201709092115 (org.eclipse.update.install.features=true) true %license %copyright Bundle-SymbolicName: org.sf.feeling.decompiler.jd;singleton:=true Bundle-Version: 3.0.0.201709092115 (org.eclipse.update.install.features=true) %license %c`

If you can suggest what should i do, Thank you

**Comment by RobertZenz** [comment]
Okay, now that is interesting, I've just tested this with a Linux/JDK7/Eclipse4.4 installation and it seems like the problem is that the TSL connection to the repository cannot be established. From what I can gather that is because Eclipse tries to connect with a TLS version which is no longer supported by GitHub, so the connection "simply" fails.

From what I could gather, the following *should* fix the problem when added to the eclipse.ini:

    -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2

I say *should* because it did nothing for me. I'm a little bit at a loss here, and the overall consensus seems to be "upgrade to Java 1.8". But I know that that is not always possible.

There are two workarounds which I can think of:

 1. Download the whole [update repository](https://github.com/ecd-plugin/update) and add it as source on the local filesystem.
    1. Download the the zip of the repository.
    2. Unpack it to somewhere on the filesystem.
    3. Go to "Install new software" and enter the location of that as source, `file://YOURLOCATION`.
 2. Download the necessary jars and place them in the dropins directory. I have never done that before, though.

Obviously you won't get automatic updates with this method, but I'm at little loss here are what we could do to mitigate this.

**Comment by rainbow99984** [comment]
Hi, So I tried the -**Dhttps** method didn't work for me as well.
Btw in my eclipse.ini, I have -**vm** option set to JDK8
Tried the local filesystem work around and it did worked, at least I have something to work with
Thank you for the help.

**Comment by eliandroribeiro** [comment]
Setting my eclipse to run on java 8 resolved my problem.
See [this stackoverflow answer](https://stackoverflow.com/a/51359313/1022567)
