### ISSUE TITLE
Provide a correct artifact build

### ISSUE THREAD

**Issue by pbi-qfs** [ecd-plugin/ecd#8]
The current approach (Eclipse site.xml -> "Build All...") seems to silently omit the category information in content.jar, so this has to be manually included before every release. This should be improved in order to make the release simpler.

**Comment by RobertZenz** [comment]
Yeah, in my experience the builtin build is kinda...flaky.

We could start to use Maven, I just have to write the required configuration files.

**Comment by RobertZenz** [comment]
I've added Maven build files. Maven1 is required to build everything and can be done by invoking `mvn clean package` in the ecd directory.

The build assumes that the updatesite is located one directory upwards in a directory "update", so the directory tree should look like this:

    root
      |-ecd
      |   \-pom.xml  <- Invoke Maven here.
      \-update
          \-pom.xml

The build takes some time to initialize but should produce reproducible and reliable results.

**Comment by RobertZenz** [comment]
There is a slight problem with the updatesite, though. The build places everything in the a sub-directory called "target", so either we start to chuckle around with soft links...which hopefully are supported by GitHub, or we copy the files to the expected locations after every build. That could be automated.

**Comment by RobertZenz** [comment]
Also the new build should allow to increase the version numbers of all plugins at once:

    mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=99.0.0.cool

**Comment by Sisylam** [comment]
Why `maven1` and not `maven2` ? And can't you specify the output directory of a maven project via

```maven
<build>
    <directory>${project.basedir}/target</directory>
</build>
```

**Comment by RobertZenz** [comment]
@Sisylam Because I've read through the documentation on how to sue Maven2 with Eclipse, and to be honest, I found it quite confusing. I have close to zero experience with Maven and from what I could gather "it just works" with Maven1, but requires more work with Maven2. Correct me please if I'm wrong there.

And thanks for the hint regarding the output directory, I have to test if that would work because the output directory is the same as the source (so `.`). Requires testing.
