### ISSUE TITLE
Can't install Jad Extension (Optional) from Eclipse Marketplace

### ISSUE THREAD

**Issue by maxxyme** [ecd-plugin/ecd#90]
on MacOS Ventura 13.3.1 (22E261) - Apple M2
using Eclipse 2023-03
(installed via homebrew "eclipse-java")
```
me@localhost % brew info eclipse-java
==> eclipse-java: 4.27.0,2023-03
https://eclipse.org/
/opt/homebrew/Caskroom/eclipse-java/4.27.0,2023-03 (126B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/eclipse-java.rb
==> Name
Eclipse IDE for Java Developers
==> Description
Eclipse IDE for Java developers
==> Artifacts
Eclipse.app -> Eclipse Java.app (App)
```

The install of the plugin via Eclipe Marketplace went fine (Core, CFR Extension, JD-Core Extension, Procyon Extension, Source are all installed) except Jad Extension isn't/can't be installed:

Error message says:

> Cannot complete the install because some dependencies are not satisfiable
>   org.eclipse.equinox.p2.iu; org.sf.feeling.decompiler.jad.feature.group [3.2.2,3.2.2] cannot be installed in this environment because its filter is not applicable.

I don't know what to do.

My main concern is that I can't have older (= compiled with JDK < 1.8) .class files opened...
In the Eclipse settings, there are only 3 decompilers listed: CFR, FernFlower and Procyon (missing JD-Core and Jad as I witnessed on an old install I had on another MBP with old 2021-xx version of Eclipse...)

**Comment by jpstotz** [comment]
Most likely this is because you are on MacOS with an ARM CPU. JAD decompiler is old - really old and it is implemented as native binary (and closed source). 

ECD currently contains three binaries: 

* one for Linux (ELF format x86 32bit)
* one for MacOS (Macho  I386 32-Bit)
* one for Windows (x86 32 bit)

I can only tell you from Jad for Windows, it is Jad v1.5.8g and according a paper about decompilers linked on Wikipedia it was released in 2001. So I would assume it is limited to class file from Java 1.3 or may be 1.4.

So I don't think it really matters if you can install or not... May be we should simply remove such relics...

**Comment by jpstotz** [comment]
In commit c74344accad2b51395993d9bdf7f161ca48557e6 I totally removed JAD from ECD.

**Comment by maxxyme** [comment]
> In commit [c74344a](https://github.com/ecd-plugin/ecd/commit/c74344accad2b51395993d9bdf7f161ca48557e6) I totally removed JAD from ECD.

OK you mean https://github.com/ecd-plugin/ecd/commit/484e8d4000405a8855f08fc173b06e54f18633b9 right...? ;)

**Comment by maxxyme** [comment]
Final note: updated & tested; at first I noticed I still couldn't open old (pre-1.8) .class files, but finally seemed to be a misconfiguration in the Eclipse Settings ("File Associations" > *.class without sources). Now works fine.
