### ISSUE TITLE
Use official Fernflower builds from IntelliJ

### ISSUE THREAD

**Issue by maxxyme** [ecd-plugin/ecd#93]
Hi,

Just came across [AUDIT.md](https://github.com/ecd-plugin/ecd/blob/2d04a74c8fdb288940a43d2b22f1999ee122ce3e/AUDIT.md) and noticed you're not using official builds from Fernflower;

ref. to [IDEA-175638](https://youtrack.jetbrains.com/issue/IDEA-175638/Please-release-fernflower-decompiler-as-a-standalone-jar) you can either get them from JetBrains' own repo, or mvnrepository.com (although this one seems a bit out of sync from time to time - hence the complaints of some users in the issue linked on YouTrack...)

Btw "builds at https://files.minecraftforge.net/net/minecraftforge/fernflower/" are 404...

**Comment by jpstotz** [comment]
Thanks, the last update of Fernflower was before I took over the project, so I don't know anything about this. 
Your link is really useful, next time I can use a release form official intellij-repo:

* https://www.jetbrains.com/intellij-repository/releases/
* https://mvnrepository.com/artifact/com.jetbrains.intellij.java/java-decompiler-engine 

At the moment I am making some experiments using the `maven-dependency-plugin` which would allow to automatically download the necessary dependencies from official Maven repositories instead of including their JAR files into the ECD repository.

**Comment by jpstotz** [comment]
The new implementation that directly downloads Fernflower via Maven at ECD build time seems to work. Thus the official Fernflower version will be used in next ECD release.

**Comment by jpstotz** [comment]
Just after releasing ECD 3.4.0 with latest FernFlower decompiler integrated I noticed that the latest Fernflower builds require Java 17. Unfortunately I can not set Java 17 as dependency for the Eclipse Plugin that contains Fernflower as for historic reasons Fernflower has no separate plugin but is included in the main plugin. Therefore setting Java17 as dependency would make the whole ECD plugin not usable on Eclipse installations running a Java version prior to 17. 

To solve this problem in a correct way I would have to move Fernflower out of the main Plugin to an own Eclipse Plugin, but that would mean that users could only install the main Plugin without any decompilers...
