### ISSUE TITLE
ECD 3.4.0: decompiling using Fernflower does not work

### ISSUE THREAD

**Issue by jpstotz** [ecd-plugin/ecd#98]
Know problem for ECD 3.4.0: 

On older Eclipse installations that are executed using a Java Runtime lower than Java 17 Fernflower will not work as the used Fernflower library was compiled for Java 17 and therefore can not be loaded on older JRE versions.

**Comment by Mateos81** [comment]
Once upgraded to 3.4.0, you have to uninstall it, download the 3.3.0 ZIP from the releases, then install from that ZIP in eclipse, because the update site only gives the latest one (yes, I've unchecked 'Show only the latest versions of available software' in 'Install New Software...')

Release: https://github.com/ecd-plugin/ecd/releases/tag/v3.3.0.20230501

Installing a plugin from an archive in eclipse: https://stackoverflow.com/questions/5482554/how-to-install-plugin-for-eclipse-from-zip

**Comment by jpstotz** [comment]
Fixed with ECD 3.5.0 (Fernflower is now an own plugin/feature and is only available on an Eclipse version that is running on Java 17).
